version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
